# Generated by Django 3.1.1 on 2020-09-19 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0004_auto_20200920_0034'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='nominations',
            new_name='no_of_likes',
        ),
        migrations.RenameField(
            model_name='course',
            old_name='upvotes',
            new_name='no_of_nominations',
        ),
        migrations.AddField(
            model_name='course',
            name='liked_by',
            field=models.ManyToManyField(related_name='user_liked', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='nominated_by',
            field=models.ManyToManyField(related_name='user_nominated', to=settings.AUTH_USER_MODEL),
        ),
    ]
